### ISSUE TITLE
Staff Calendar page 

### ISSUE THREAD

**Issue by angrave** [illinois-cs/Webpage#10]
* Rename "office hours" menu bar to "Help"
* The SP16 lectures are 2pm and 3pm (it currently shows 12pm in the Google calendar)

Then divide this page up into different kinds of help. I suggest - 

Search first ---Don't Post--- 
Your favorite search engine can quickly get the answer you need.
Your question may already have been answered on Piazza.

For other administrative items (e.g. exam sickness) please contact Marina, email:cs241admin@illinois.edu

Use your section TA for grade-related issues and conceptual questions.
Your section TA should be your main point of contact for all grade-related items. You can find their email easily using the Interweb.

Lab assistance (in SC0218 )
The Google Calendar should be labelled "Peer Tutoring" not Office Hours.
This is not CS225 - We will not debug your MP/Lab! But we can give you advice on how to debug it yourself.

See Angrave
Lawrence is available after *every* lecture. Other times by appointment. You can also drop by and look for him in the neighborhood of SC2217.

**Comment by bchong95** [comment]
Ok I made these changes
